set(CTEST_CMAKE_GENERATOR "Visual Studio 12")

set(CTEST_BUILD_CONFIGURATION "Debug")
set(COMPILER_NAME "Visual Studio")
set(COMPILER_VERSION "12.2013")

set(WITH_MEMCHECK FALSE)
set(WITH_COVERAGE FALSE)
